sonar.projectKey=yosrikhiari_Versatile
sonar.organization=yosrikhiari
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.exclusions=**/tests/**,**/*.config.*,**/main.js
sonar.tests=src/tests
sonar.test.inclusions=**/*.test.{js,ts,jsx,tsx}

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.eslint.reportPaths=eslint-report.json
sonar.coverage.exclusions=**/tests/**,**/*.config.*,**/main.js
