/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  safelist: ['animate-spin'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--vers-bg-base)',
        'bg-secondary': 'var(--vers-bg-panel)',
        'bg-tertiary': 'var(--vers-bg-canvas)',
        'surface-hover': 'var(--vers-bg-hover)',
        'border-subtle': 'var(--vers-border-subtle)',
        'border-strong': 'var(--vers-border-subtle)',
        'text-primary': 'var(--vers-text-primary)',
        'text-secondary': 'var(--vers-text-secondary)',
        'text-hint': 'var(--vers-text-muted)',
        accent: 'var(--vers-accent-primary)',
        'accent-hover': '#D4A040',
        'accent-muted': 'var(--vers-accent-secondary)',
        'accent-glow': 'rgba(var(--vers-accent-primary-rgb), 0.15)',
        'accent-glass': 'rgba(var(--vers-accent-primary-rgb), 0.08)',
        danger: '#d07070',
        success: '#6a9e7a',
        info: '#5b8cb8',
        'bg-info': '#1e2d3d',
        'text-info': '#7eb8e0',
        warning: '#d4a74a',
        'entity-character': '#f48fb1',
        'entity-location': '#4fc3f7',
        'entity-thread': '#ce93d8',
        manuscript: 'var(--vers-bg-base)',
        'manuscript-editor': 'var(--vers-bg-panel)',
        glow: 'var(--vers-accent-primary)',
      },
      spacing: {
        '4.5': '1.125rem',
        '18': '4.5rem',
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
      },
      fontFamily: {
        body: ['Crimson Pro', 'Georgia', 'serif'],
        ui: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        spark: ['Playfair Display', 'Georgia', 'serif'],
        flow: ['Lora', 'Georgia', 'serif'],
        polish: ['Libre Baskerville', 'Georgia', 'serif'],
        revise: ['EB Garamond', 'Georgia', 'serif'],
        storybible: ['Merriweather', 'Georgia', 'serif'],
        display: ['Playfair Display', 'Georgia', 'serif'],
      },
      boxShadow: {
        'warm-sm': '0 1px 2px rgba(0,0,0,0.5), 0 0 0 1px rgba(var(--vers-accent-primary-rgb), 0.03)',
        'warm-md': '0 4px 12px rgba(0,0,0,0.4), 0 0 0 1px rgba(var(--vers-accent-primary-rgb), 0.04)',
        'warm-lg': '0 8px 24px rgba(0,0,0,0.5), 0 0 0 1px rgba(var(--vers-accent-primary-rgb), 0.05)',
        'warm-xl': '0 12px 40px rgba(0,0,0,0.6), 0 0 0 1px rgba(var(--vers-accent-primary-rgb), 0.06)',
        'accent-glow': '0 0 20px rgba(var(--vers-accent-primary-rgb), 0.15), 0 0 40px rgba(var(--vers-accent-primary-rgb), 0.05)',
      },
      backdropBlur: {
        xs: '2px',
      },
      transitionDuration: {
        '150': '150ms',
        '200': '200ms',
        '250': '250ms',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.19, 1, 0.22, 1)',
        'out-quart': 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
      },
      animation: {
        spin: 'spin 1s linear infinite',
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fade-in 0.2s ease-out forwards',
        'fade-out': 'fade-out 0.15s ease-out forwards',
        'scale-in': 'scale-in 0.2s ease-out forwards',
        'slide-in-right': 'slide-in-right 0.2s ease-out forwards',
        'slide-in-left': 'slide-in-left 0.2s ease-out forwards',
        'slide-in-up': 'slide-in-up 0.2s ease-out forwards',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
      },
      keyframes: {
        spin: { to: { transform: 'rotate(360deg)' } },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-right': {
          '0%': { opacity: '0', transform: 'translateX(8px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-left': {
          '0%': { opacity: '0', transform: 'translateX(-8px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-up': {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
