export const TABLES = {
  PROJECTS: 'projects',
  MANUSCRIPTS: 'manuscripts',
  CHARACTERS: 'characters',
  CHARACTER_RELATIONSHIPS: 'characterRelationships',
  LOCATIONS: 'locations',
  PLOT_THREADS: 'plotThreads',
  SPARK_HISTORY: 'sparkHistory',
  ANNOTATIONS: 'annotations',
  SNIPPETS: 'snippets',
  DAILY_GOALS: 'dailyGoals',
  REVISION_COMMENTS: 'revisionComments',
  STORY_ELEMENTS: 'storyElements',
  GRAPH_EDGES: 'graphEdges',
  GROUP_EDGES: 'groupEdges',

  SNAPSHOTS: 'snapshots',
  VOLUMES: 'volumes',
  VOLUME_ENTITIES: 'volumeEntities',
  SECTIONS: 'sections',
  SUBSECTIONS: 'subsections',
  SESSION_ARCHIVE: 'sessionArchive',
  AUTHOR_PROFILE: 'authorProfile',
  STORY_STATE_SNAPSHOTS: 'storyStateSnapshots',
  STORY_DOCUMENTS: 'storyDocuments',
  GENERATED_STORIES: 'generatedStories',
  VOICE_PROFILES: 'voiceProfiles',
  RESEARCH_DOCUMENTS: 'researchDocuments',
  RESEARCH_CHUNKS: 'researchChunks',
  RESEARCH_TAGS: 'researchTags',
  PENDING_DELETIONS: 'pendingDeletions',
  EMBEDDING_CACHE: 'embeddingCache',
  USERS: 'users',
  DIALOGUE_INDEX: 'dialogueIndex',
  STORY_SHAPE_ANALYSIS: 'storyShapeAnalysis',
  CHAT_SESSIONS: 'chatSessions',
  GEN_RUNS: 'genRuns',
  PROJECT_BLURBS: 'projectBlurbs',
  EVAL_RESULTS: 'evalResults',
  BRANCHES: 'branches',
  GRAPH_NODE_POSITIONS: 'graphNodePositions',
  GRAPH_GROUPS_V2: 'graphGroupsV2',
  GRAPH_NODE_PARENTS: 'graphNodeParents',
  GRAPH_NODE_INSTANCES: 'graphNodeInstances'
} as const

export const SYNC_FIELDS = 'apiId, syncStatus, lastSyncedAt'
export const GENERATION_STATUS_FIELD = 'generationStatus'
export const CONTENT_STATUS_FIELD = 'contentStatus'
